export const PROJECT_PREVIEW_SELECTION_SCRIPT = [
  "(function () {",
  "  if (window.__CRYSTAL_PREVIEW_SELECTION__) {",
  "    return;",
  "  }",
  "  window.__CRYSTAL_PREVIEW_SELECTION__ = true;",
  "  var enabled = false;",
  "  var selectedElement = null;",
  "  var previousOutline = null;",
  "  var previousOutlineOffset = null;",
  "  var maxAttributes = 8;",
  "  var maxAttributeLength = 120;",
  "  var maxTextLength = 160;",
  "  var maxSelectorLength = 180;",
  "  function truncate(value, maxLength) {",
  "    var text = String(value || '').replace(/\\s+/g, ' ').trim();",
  "    if (text.length <= maxLength) return text;",
  "    return text.slice(0, Math.max(0, maxLength - 1)) + '…';",
  "  }",
  "  function clearHighlight() {",
  "    if (!selectedElement) return;",
  "    if (previousOutline === null) selectedElement.style.removeProperty('outline');",
  "    else selectedElement.style.outline = previousOutline;",
  "    if (previousOutlineOffset === null) selectedElement.style.removeProperty('outline-offset');",
  "    else selectedElement.style.outlineOffset = previousOutlineOffset;",
  "    selectedElement = null;",
  "    previousOutline = null;",
  "    previousOutlineOffset = null;",
  "  }",
  "  function applyHighlight(element) {",
  "    clearHighlight();",
  "    selectedElement = element;",
  "    previousOutline = element.style.outline || null;",
  "    previousOutlineOffset = element.style.outlineOffset || null;",
  "    element.style.outline = '2px solid #7c3aed';",
  "    element.style.outlineOffset = '2px';",
  "  }",
  "  function hasMeaningfulText(node) {",
  "    return !!node && node.nodeType === 3 && String(node.nodeValue || '').replace(/\\s+/g, ' ').trim().length > 0;",
  "  }",
  "  function shouldCountPathNode(node) {",
  "    if (!node) return false;",
  "    if (node.nodeType === 1) return true;",
  "    if (node.nodeType === 8) return true;",
  "    if (node.nodeType === 10) return true;",
  "    return hasMeaningfulText(node);",
  "  }",
  "  function getCountedChildren(parent) {",
  "    var children = [];",
  "    if (!parent || !parent.childNodes) return children;",
  "    for (var index = 0; index < parent.childNodes.length; index += 1) {",
  "      var child = parent.childNodes[index];",
  "      if (shouldCountPathNode(child)) children.push(child);",
  "    }",
  "    return children;",
  "  }",
  "  function getChildIndex(node) {",
  "    if (!node || !node.parentNode) return 0;",
  "    var siblings = getCountedChildren(node.parentNode);",
  "    for (var index = 0; index < siblings.length; index += 1) {",
  "      if (siblings[index] === node) return index;",
  "    }",
  "    return 0;",
  "  }",
  "  function getSnapshotPath(node) {",
  "    var indexes = [];",
  "    var current = node;",
  "    while (current && current !== document) {",
  "      indexes.unshift(String(getChildIndex(current)));",
  "      current = current.parentNode;",
  "    }",
  "    return ['0'].concat(indexes).join('/');",
  "  }",
  "  function isCrystalHighlightStyle(name, value) {",
  "    if (String(name || '').toLowerCase() !== 'style') return false;",
  "    var text = String(value || '').toLowerCase();",
  "    if (text.indexOf('outline') < 0) return false;",
  "    return text.indexOf('7c3aed') >= 0 || text.indexOf('124, 58, 237') >= 0 || text.indexOf('outline-offset') >= 0;",
  "  }",
  "  function getAttributesPreview(element) {",
  "    var attributes = [];",
  "    if (!element || !element.attributes) return attributes;",
  "    for (var index = 0; index < element.attributes.length && attributes.length < maxAttributes; index += 1) {",
  "      var attribute = element.attributes[index];",
  "      if (isCrystalHighlightStyle(attribute.name, attribute.value)) continue;",
  "      var name = truncate(attribute.name, 40);",
  "      var value = truncate(attribute.value, maxAttributeLength);",
  "      attributes.push({ name: name, value: value });",
  "    }",
  "    return attributes;",
  "  }",
  "  function getTextPreview(element) {",
  "    var tagName = element.tagName ? element.tagName.toLowerCase() : '';",
  "    if (tagName === 'script' || tagName === 'style') return '';",
  "    return truncate(element.textContent || '', maxTextLength);",
  "  }",
  "  function getSelectorPreview(element) {",
  "    var tagName = element.tagName ? element.tagName.toLowerCase() : 'element';",
  "    var selector = tagName;",
  "    if (element.id) selector += '#' + truncate(element.id, 60);",
  "    if (element.classList && element.classList.length) {",
  "      var classNames = [];",
  "      for (var index = 0; index < element.classList.length && classNames.length < 4; index += 1) {",
  "        classNames.push(truncate(element.classList[index], 40));",
  "      }",
  "      if (classNames.length) selector += '.' + classNames.join('.');",
  "    }",
  "    return truncate(selector, maxSelectorLength);",
  "  }",
  "  function createPayload(element) {",
  "    var snapshotPath = getSnapshotPath(element);",
  "    var parts = snapshotPath.split('/');",
  "    var siblingIndex = Number(parts[parts.length - 1] || '0');",
  "    return {",
  "      snapshotPath: snapshotPath,",
  "      tagName: element.tagName ? element.tagName.toLowerCase() : '',",
  "      siblingIndex: Number.isFinite(siblingIndex) ? siblingIndex : 0,",
  "      depth: Math.max(0, parts.length - 1),",
  "      attributesPreview: getAttributesPreview(element),",
  "      textPreview: getTextPreview(element),",
  "      selectorPreview: getSelectorPreview(element)",
  "    };",
  "  }",
  "  function handleClick(event) {",
  "    if (!enabled) return;",
  "    var target = event.target;",
  "    if (!target || target.nodeType !== 1) return;",
  "    event.preventDefault();",
  "    event.stopPropagation();",
  "    if (target === selectedElement) clearHighlight();",
  "    var payload = createPayload(target);",
  "    applyHighlight(target);",
  "    window.parent.postMessage({ type: 'crystal:preview-selection:selected', payload: payload }, '*');",
  "  }",
  "  function enableSelection() {",
  "    if (enabled) return;",
  "    enabled = true;",
  "    document.addEventListener('click', handleClick, true);",
  "  }",
  "  function disableSelection() {",
  "    if (!enabled) return;",
  "    enabled = false;",
  "    document.removeEventListener('click', handleClick, true);",
  "    clearHighlight();",
  "  }",
  "  function clearSelection() {",
  "    clearHighlight();",
  "  }",
  "  window.addEventListener('message', function (event) {",
  "    var data = event.data;",
  "    if (!data || typeof data.type !== 'string') return;",
  "    if (data.type === 'crystal:preview-selection:enable') enableSelection();",
  "    if (data.type === 'crystal:preview-selection:disable') disableSelection();",
  "    if (data.type === 'crystal:preview-selection:clear') clearSelection();",
  "  });",
  "})();"
].join("\n");
