import type { CSSSassInspectorSurfaceElements } from "../../views/inspector/css-sass-inspector";

export interface ProjectPreviewPanelElements extends CSSSassInspectorSurfaceElements {
  readonly status: HTMLElement;
  readonly target: HTMLSelectElement;
  readonly page: HTMLElement;
  readonly lastLoad: HTMLElement;
  readonly lastReload: HTMLElement;
  readonly reason: HTMLElement;
  readonly issueCount: HTMLElement;
  readonly lastIssue: HTMLElement;
  readonly error: HTMLElement;
  readonly selectionMode: HTMLElement;
  readonly selectedTag: HTMLElement;
  readonly selectedPath: HTMLElement;
  readonly selectionMappingStatus: HTMLElement;
  readonly mappedSnapshotPath: HTMLElement;
  readonly selectionMappingReason: HTMLElement;
  readonly selectedSelector: HTMLElement;
  readonly selectedAttributes: HTMLElement;
  readonly selectedText: HTMLElement;
  readonly selectionIssue: HTMLElement;
  readonly inspectorStatus: HTMLElement;
  readonly inspectorMessage: HTMLElement;
  readonly inspectorSelectedDetails: HTMLDListElement;
  readonly inspectorSnapshotDetails: HTMLDListElement;
  readonly inspectorSnapshotEmpty: HTMLElement;
  readonly editableInspectorStatus: HTMLElement;
  readonly editableInspectorMessage: HTMLElement;
  readonly editableInspectorReadiness: HTMLDListElement;
  readonly editableInspectorFields: HTMLElement;
  readonly editableInspectorFieldsEmpty: HTMLElement;
  readonly editableInspectorIntents: HTMLUListElement;
  readonly editableInspectorIntentsEmpty: HTMLElement;
  readonly editableInspectorApplyUnavailableAffordance: HTMLElement;
  readonly issuesEmpty: HTMLElement;
  readonly issuesList: HTMLUListElement;
  readonly frame: HTMLIFrameElement;
  readonly loadButton: HTMLButtonElement;
  readonly reloadButton: HTMLButtonElement;
  readonly selectModeButton: HTMLButtonElement;
  readonly clearSelectionButton: HTMLButtonElement;
}
